# Generated by Django 2.1.2 on 2018-10-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_on_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='on_off',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='on_off',
            name='on_off',
            field=models.FloatField(default=0),
        ),
    ]
