# Generated by Django 2.0.6 on 2018-11-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181022_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='on_off',
            name='on_off',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
