# Generated by Django 2.0.6 on 2018-11-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_on_off_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='On_Off_google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_off', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='on_off',
            name='user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='on_off',
            name='on_off',
            field=models.FloatField(default=0),
        ),
    ]
