# Generated by Django 2.0.6 on 2018-11-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181125_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='on_off',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
