# Generated by Django 2.0.6 on 2018-11-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_on_off_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='on_off',
            name='timestamp',
        ),
    ]
